transactions:
  outputs:
    dev:
      dbname: "{{ env_var('DATABASE') }}"
      host: "{{ env_var('HOSTNAME') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: "{{ env_var('PORT') | int }}"
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('USERNAME') }}"
  target: dev
